# Generated by Django 3.0.2 on 2020-01-31 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200131_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.UserGroup'),
        ),
    ]
