# Generated by Django 3.0.2 on 2020-02-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200131_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='title',
            field=models.CharField(max_length=32, verbose_name='用户分组'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='title',
            field=models.CharField(max_length=32, verbose_name='角色名称'),
        ),
    ]
