# Generated by Django 3.0.2 on 2020-02-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200202_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='title',
            field=models.CharField(max_length=32, verbose_name='分组名称'),
        ),
    ]
