# Generated by Django 2.2.5 on 2020-12-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerinfo',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.CreateModel(
            name='PlayerToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.PlayerInfo')),
            ],
        ),
    ]
