# Generated by Django 3.0.2 on 2020-12-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_auto_20201212_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(default='', max_length=64)),
                ('kit1_color', models.CharField(default='ffffff', max_length=32)),
                ('kit2_color', models.CharField(default='000000', max_length=32)),
                ('win', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_aginst', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('league_belong', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('players', models.ManyToManyField(to='league.PlayerLogin')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
            },
        ),
    ]
