# Generated by Django 3.0.2 on 2020-12-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='league_belong',
        ),
        migrations.AddField(
            model_name='club',
            name='league_belong',
            field=models.ManyToManyField(to='league.League'),
        ),
    ]
