# Generated by Django 3.0.2 on 2020-12-15 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League', verbose_name='League of this team'),
        ),
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='Player', max_length=64)),
                ('player_birthday', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Birthday')),
                ('player_nation', models.CharField(default='Player', max_length=64)),
                ('player_league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.League', verbose_name='League of this player')),
                ('player_login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.PlayerLogin')),
                ('player_roles', models.ManyToManyField(to='league.Role')),
                ('player_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.Team', verbose_name='Team of this player')),
            ],
            options={
                'verbose_name': 'PlayerDetail',
                'verbose_name_plural': 'PlayerDetail',
            },
        ),
    ]
