# Generated by Django 3.0.2 on 2020-12-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_auto_20201217_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(default=[], to='league.PlayerLogin'),
        ),
    ]
