# Generated by Django 3.0.2 on 2021-01-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_auto_20201217_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='goals_aginst',
            new_name='goals_against',
        ),
    ]
