# Generated by Django 3.0.2 on 2021-01-04 07:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_auto_20210104_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='MatchTime')),
                ('is_gameover', models.BooleanField(default=False)),
                ('home_team_score', models.IntegerField(default=0)),
                ('away_team_score', models.IntegerField(default=0)),
                ('match_round', models.IntegerField(default=0)),
                ('match_number_this_round', models.IntegerField(default=0)),
                ('match_number_this_league', models.IntegerField(default=0)),
                ('remarks', models.CharField(default='', max_length=512)),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.Team', verbose_name='Home Team')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
