# Generated by Django 3.0.2 on 2021-01-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_auto_20210104_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(default='Location', max_length=64),
        ),
    ]
